In [9]:
import pandas as pd
import os
from mysql import connector as cnn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from dotenv import load_dotenv
load_dotenv()
db_pass=os.getenv("DB_PASSWORD")
db=os.getenv("DB")
conn=cnn.connect(
    host='localhost',
    user='root',
    password=db_pass,
    database=db
)
cur=conn.cursor()
cur.execute("USE STUDENT")
df=pd.read_sql("SELECT * FROM ACAD_PERF",con=conn)
df

C:\Users\chait\AppData\Local\Temp\ipykernel_22612\2528743210.py:18: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql("SELECT * FROM ACAD_PERF",con=conn)

,ST_ID,PREV_GPA,ATTENDANCE,INTERNALS,BACKLOGS,STUDY_HRS_PER_WEEK,CURRENT_COURSE_LOAD,ACADEMIC_RISK
0,1,8.0,76.0,77.0,0,11.0,6,14.0
1,2,7.0,95.0,69.0,0,12.0,5,21.0
2,3,8.0,70.0,76.0,0,11.0,6,18.0
3,4,9.0,68.0,85.0,0,17.0,7,21.0
4,5,7.0,72.0,81.0,0,14.0,8,71.0
...,...,...,...,...,...,...,...,...
795,796,8.0,61.0,64.0,0,16.0,4,20.0
796,797,7.0,67.0,80.0,1,13.0,5,85.0
797,798,8.0,66.0,75.0,0,6.0,7,35.0
798,799,7.0,81.0,70.0,0,16.0,8,26.0
799,800,7.0,79.0,72.0,1,5.0,7,18.0

In [10]:
x=df.drop(columns=['ST_ID','ACADEMIC_RISK'])
y=df['ACADEMIC_RISK']
x

,PREV_GPA,ATTENDANCE,INTERNALS,BACKLOGS,STUDY_HRS_PER_WEEK,CURRENT_COURSE_LOAD
0,8.0,76.0,77.0,0,11.0,6
1,7.0,95.0,69.0,0,12.0,5
2,8.0,70.0,76.0,0,11.0,6
3,9.0,68.0,85.0,0,17.0,7
4,7.0,72.0,81.0,0,14.0,8
...,...,...,...,...,...,...
795,8.0,61.0,64.0,0,16.0,4
796,7.0,67.0,80.0,1,13.0,5
797,8.0,66.0,75.0,0,6.0,7
798,7.0,81.0,70.0,0,16.0,8
799,7.0,79.0,72.0,1,5.0,7

In [11]:
y

0      14.0
1      21.0
2      18.0
3      21.0
4      71.0
       ...
795    20.0
796    85.0
797    35.0
798    26.0
799    18.0
Name: ACADEMIC_RISK, Length: 800, dtype: float64

In [12]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
x_train

,PREV_GPA,ATTENDANCE,INTERNALS,BACKLOGS,STUDY_HRS_PER_WEEK,CURRENT_COURSE_LOAD
384,6.0,89.0,54.0,2,20.0,6
769,9.0,93.0,87.0,0,10.0,7
43,7.0,83.0,76.0,0,19.0,7
483,7.0,50.0,83.0,1,13.0,4
685,8.0,84.0,87.0,0,9.0,6
...,...,...,...,...,...,...
787,8.0,67.0,83.0,0,5.0,6
470,7.0,90.0,69.0,2,15.0,6
624,9.0,70.0,70.0,0,15.0,7
181,6.0,77.0,67.0,2,9.0,6
31,9.0,68.0,81.0,0,16.0,8

In [13]:
y_train

384    78.0
769    19.0
43     13.0
483    30.0
685    30.0
       ...
787    74.0
470    77.0
624    17.0
181    83.0
31     36.0
Name: ACADEMIC_RISK, Length: 640, dtype: float64

In [14]:
#Without scaling data and removing outliers
model1=LinearRegression()
model1.fit(x_train,y_train)
pred1=model1.predict(x_test)
print(pred1.shape,y_test.shape)
print(model1.score(x_test,y_test))
pred1

(160,) (160,)
0.595405049850022

array([ 52.33577869,  18.39291154,  48.91762918, 103.84918694,
        33.19785175,  48.61089575,  72.47766699,  82.90459845,
        40.15816904,  33.96539889,  29.90824009,  57.66951913,
        64.69072174,  89.22270337,  28.91994275,  61.12824348,
        72.36587026,  56.00863194,  66.0840649 ,  69.48797335,
        43.49847781,  39.55227448,  64.58941635,  36.51291665,
        28.28468774,  33.83800141,  70.74996116,  44.43096763,
        47.28657193,  94.09430081,  56.32213658,  54.09071424,
        51.43596507,  33.30883288,  21.93783064,  88.00135393,
        32.3471401 ,  26.68244641,  30.97232887,  79.68448838,
        71.15101273,  72.40879539,  42.30532628,  29.29400182,
        65.22056419,  48.00837978,  40.15508382,  60.15857172,
        62.94140697,  58.92327706,  42.54352419,  67.80619946,
        19.79329598,  55.28851566,  36.92482305,  34.53084772,
        25.65760317,  65.52490346,  48.65654137,  28.48650712,
        28.04196203,  54.89590146,  39.16185977,  44.69694464,
        47.2314951 ,  92.10525131,  66.38338563,  41.35956604,
        29.96065781,  34.83857287,  66.44515422,  20.53302651,
        88.01574508,  60.61957281,  48.96339266,  36.20772916,
        52.67397416,  56.76408564,  44.13620977,  43.09797166,
        99.71185946,  21.38437946,  23.52325672,  88.56686559,
        49.42940861,  79.38425627,  65.75447874,  82.72199714,
        82.39725095,  56.06153705,  99.82821896,  32.14273913,
        56.27832817,  81.64853575,  30.42069343,  58.03230249,
        56.76393912,  58.51615384,  42.10673775,  35.47497281,
        94.0184816 ,  22.77756512,  47.7881991 ,  60.05288416,
        66.31968762,  23.41844302,  40.37909994,  98.0720363 ,
        52.08361875,  30.20145411,  31.08337071,  45.23327989,
        40.69384318,  67.80517055,  57.56129389,  31.72639623,
        37.54498733,  19.35001278,  14.50695863,  12.83176665,
        53.46105492,  33.41025824,  62.64423598,  10.73617892,
        36.98730901,  28.60605017,  76.76331045,  30.33120857,
        64.76401057,  63.31032268,  58.9062026 ,  62.07309469,
        59.51364099,  27.43466927,  22.16659277,  43.16753397,
        28.13857765,  25.38219677,  79.34169497,  39.75052483,
        48.47552052,  62.60726251,  33.88591698,  73.48745603,
        85.06143133,  29.77322714,  65.07429906,  43.69280414,
        63.50186748,  70.31968032,  47.86722507,  34.61147456,
        33.12502108,  82.79588482,  26.29004157,  28.79621008,
        47.78255423,  83.61757421,  36.60092296,  17.65030516])