In [1]:
import pandas as pd
import os
from mysql import connector as cnn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from dotenv import load_dotenv
load_dotenv()
db_pass=os.getenv("DB_PASSWORD")
db=os.getenv("DB")
conn=cnn.connect(
    host='localhost',
    user='root',
    password=db_pass,
    database=db
)
cur=conn.cursor()
cur.execute("USE STUDENT")
df=pd.read_sql("SELECT * FROM ACAD_PERF",con=conn)
df

C:\Users\chait\AppData\Local\Temp\ipykernel_27076\2528743210.py:18: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df=pd.read_sql("SELECT * FROM ACAD_PERF",con=conn)

,ST_ID,PREV_GPA,ATTENDANCE,INTERNALS,BACKLOGS,STUDY_HRS_PER_WEEK,CURRENT_COURSE_LOAD,ACADEMIC_RISK
0,1,8.0,76.0,77.0,0,11.0,6,14.0
1,2,7.0,95.0,69.0,0,12.0,5,21.0
2,3,8.0,70.0,76.0,0,11.0,6,18.0
3,4,9.0,68.0,85.0,0,17.0,7,21.0
4,5,7.0,72.0,81.0,0,14.0,8,71.0
...,...,...,...,...,...,...,...,...
795,796,8.0,61.0,64.0,0,16.0,4,20.0
796,797,7.0,67.0,80.0,1,13.0,5,85.0
797,798,8.0,66.0,75.0,0,6.0,7,35.0
798,799,7.0,81.0,70.0,0,16.0,8,26.0
799,800,7.0,79.0,72.0,1,5.0,7,18.0

In [2]:
x=df.drop(columns=['ST_ID','ACADEMIC_RISK'])
y=df['ACADEMIC_RISK']
x

,PREV_GPA,ATTENDANCE,INTERNALS,BACKLOGS,STUDY_HRS_PER_WEEK,CURRENT_COURSE_LOAD
0,8.0,76.0,77.0,0,11.0,6
1,7.0,95.0,69.0,0,12.0,5
2,8.0,70.0,76.0,0,11.0,6
3,9.0,68.0,85.0,0,17.0,7
4,7.0,72.0,81.0,0,14.0,8
...,...,...,...,...,...,...
795,8.0,61.0,64.0,0,16.0,4
796,7.0,67.0,80.0,1,13.0,5
797,8.0,66.0,75.0,0,6.0,7
798,7.0,81.0,70.0,0,16.0,8
799,7.0,79.0,72.0,1,5.0,7

In [3]:
y

0      14.0
1      21.0
2      18.0
3      21.0
4      71.0
       ...
795    20.0
796    85.0
797    35.0
798    26.0
799    18.0
Name: ACADEMIC_RISK, Length: 800, dtype: float64

In [4]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)
x_train

,PREV_GPA,ATTENDANCE,INTERNALS,BACKLOGS,STUDY_HRS_PER_WEEK,CURRENT_COURSE_LOAD
69,6.0,85.0,73.0,0,19.0,6
634,6.0,64.0,60.0,2,11.0,5
392,6.0,92.0,51.0,2,7.0,8
609,9.0,78.0,84.0,0,9.0,5
90,7.0,85.0,77.0,0,12.0,5
...,...,...,...,...,...,...
621,8.0,70.0,79.0,0,12.0,7
529,6.0,87.0,73.0,0,5.0,5
287,8.0,83.0,68.0,0,8.0,5
125,10.0,91.0,93.0,0,6.0,7
285,5.0,81.0,54.0,4,20.0,7

In [5]:
y_train

69     22.0
634    83.0
392    70.0
609    21.0
90     19.0
       ...
621    19.0
529    70.0
287    80.0
125    21.0
285    97.0
Name: ACADEMIC_RISK, Length: 640, dtype: float64

In [6]:
#Without scaling data and removing outliers
model1=LinearRegression()
model1.fit(x_train,y_train)
pred1=model1.predict(x_test)
print(pred1.shape,y_test.shape)
print(model1.score(x_test,y_test))
pred1

(160,) (160,)
0.6083626048519761

array([ 95.12243588,  77.85590568,  44.59766324,  97.50558634,
        71.92828751,  42.54877974,  65.48149309,  75.36611766,
        23.09999355,  59.71645827,  28.23323334,  45.17561692,
        49.28845327,  92.55447998,  28.12559082,  56.88152926,
        66.9229843 ,  66.6355361 ,  48.11416598,  35.28524692,
        75.0217675 ,  33.21536598,  64.87760674,  30.28034038,
        38.38778933,  71.73605918,  59.84909149,  56.74778444,
        65.10430667,  36.13627158,  29.30182059,  82.74424246,
        33.53730692,  30.16474845,  62.84514622,  23.28035553,
        24.71168634,  21.86691981,  65.04542871,  91.71021403,
        34.49102036,  48.21614027,  85.26823123,  61.64683273,
        75.7644389 ,  15.70765491,  61.51964794,  48.86072177,
       115.2002978 ,  72.98630019,  25.80383125,  17.27992738,
        26.09638809,  76.12833913,  57.87818789,  28.02974765,
        40.50126491,  84.13947092,  53.61546487,   3.73511147,
        41.34739381,  54.81967824,  71.02422778,  62.14626814,
        53.28005406,  49.88135643,  44.63510982,  61.79677392,
        56.58994763,  28.41041805,   8.07515358,  69.1724322 ,
        65.92081244,  47.99755157,  41.63166837,  88.54151359,
        62.48411292,  47.4998131 , 109.0021822 ,  28.24207523,
        46.05850625,  53.71001987,  60.93316339,  49.20380447,
        20.94794145,  39.4613905 ,  79.207179  ,  73.15228551,
        37.88125914,  31.92608629,  59.39882511,  38.8887956 ,
        92.27139754,  30.11280243,  32.81334067,  41.12381317,
        34.34685629,  44.37161984,  36.41565038,  44.71552634,
        93.28941107,  55.16775053,  17.531676  ,  51.24222144,
        -1.55578407,  78.863067  ,  27.63473744,  60.41608394,
        43.09521146,  35.65719139,  66.24607134,  44.33267861,
        35.56765449,  74.73098021,  64.85788981,  25.53750048,
       105.10625553,  62.31448096,  35.21445243,  48.1805925 ,
        88.3179068 ,  37.16855708,  83.60874768,  34.11149479,
        51.09497423,  47.69058363,  50.6400034 ,  54.48480161,
        60.06329607,  54.85699063,  30.16094648,  21.93125953,
        81.59814887,  65.64946356,  29.73337851,  74.32994776,
        44.87739185,  71.84728997,  46.95936398,  14.65314456,
        69.61270922,  64.54158166,  11.21982781,  46.2859713 ,
        47.00678239,   1.70775319,  16.52761283,  42.92655831,
        33.4919753 ,  63.76739569,  26.43093185,  51.63732217,
        42.2232212 ,  62.67056136,  45.55440184,  53.3874901 ,
        24.78776743,  95.36119445,  73.81410367,  33.1384009 ])

In [7]:
#With scaling and removing outliers
df.describe()

,ST_ID,PREV_GPA,ATTENDANCE,INTERNALS,BACKLOGS,STUDY_HRS_PER_WEEK,CURRENT_COURSE_LOAD,ACADEMIC_RISK
count,800.0000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000
mean,400.5000,7.193750,78.067500,71.998750,0.611250,11.941250,6.031250,51.870000
std,231.0844,1.145798,11.298563,14.158985,0.849132,5.041534,1.261849,29.391417
min,1.0000,4.000000,42.000000,32.000000,0.000000,2.000000,3.000000,4.000000
25%,200.7500,6.000000,71.000000,62.000000,0.000000,8.000000,5.000000,23.000000
50%,400.5000,7.000000,78.000000,72.000000,0.000000,12.000000,6.000000,54.000000
75%,600.2500,8.000000,86.000000,82.000000,1.000000,15.000000,7.000000,80.000000
max,800.0000,10.000000,100.000000,98.000000,4.000000,28.000000,9.000000,97.000000

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ST_ID                800 non-null    int64
 1   PREV_GPA             800 non-null    float64
 2   ATTENDANCE           800 non-null    float64
 3   INTERNALS            800 non-null    float64
 4   BACKLOGS             800 non-null    int64
 5   STUDY_HRS_PER_WEEK   800 non-null    float64
 6   CURRENT_COURSE_LOAD  800 non-null    int64
 7   ACADEMIC_RISK        800 non-null    float64
dtypes: float64(5), int64(3)
memory usage: 50.1 KB

In [9]:
#Scaling
import numpy as np
from sklearn.preprocessing import MinMaxScaler,StandardScaler
model2=LinearRegression()
scale_x=MinMaxScaler()
scale_y=MinMaxScaler()
x_train_scaled=scale_x.fit_transform(x_train)
y_train_scaled=scale_y.fit_transform(np.array(y_train).reshape(-1,1))
x_test_scaled=scale_x.transform(x_test)
y_test_scaled=scale_y.transform(np.array(y_test).reshape(-1,1))

In [10]:
#Training
model2.fit(x_train_scaled,y_train_scaled)
pred2=model2.predict(x_test_scaled)
pred2=scale_y.inverse_transform(np.array(pred2).reshape(-1,1))

In [11]:
#output
print(model2.score(x_test_scaled,y_test_scaled))
pred2

0.608362604851976

array([[ 95.12243588],
       [ 77.85590568],
       [ 44.59766324],
       [ 97.50558634],
       [ 71.92828751],
       [ 42.54877974],
       [ 65.48149309],
       [ 75.36611766],
       [ 23.09999355],
       [ 59.71645827],
       [ 28.23323334],
       [ 45.17561692],
       [ 49.28845327],
       [ 92.55447998],
       [ 28.12559082],
       [ 56.88152926],
       [ 66.9229843 ],
       [ 66.6355361 ],
       [ 48.11416598],
       [ 35.28524692],
       [ 75.0217675 ],
       [ 33.21536598],
       [ 64.87760674],
       [ 30.28034038],
       [ 38.38778933],
       [ 71.73605918],
       [ 59.84909149],
       [ 56.74778444],
       [ 65.10430667],
       [ 36.13627158],
       [ 29.30182059],
       [ 82.74424246],
       [ 33.53730692],
       [ 30.16474845],
       [ 62.84514622],
       [ 23.28035553],
       [ 24.71168634],
       [ 21.86691981],
       [ 65.04542871],
       [ 91.71021403],
       [ 34.49102036],
       [ 48.21614027],
       [ 85.26823123],
       [ 61.64683273],
       [ 75.7644389 ],
       [ 15.70765491],
       [ 61.51964794],
       [ 48.86072177],
       [115.2002978 ],
       [ 72.98630019],
       [ 25.80383125],
       [ 17.27992738],
       [ 26.09638809],
       [ 76.12833913],
       [ 57.87818789],
       [ 28.02974765],
       [ 40.50126491],
       [ 84.13947092],
       [ 53.61546487],
       [  3.73511147],
       [ 41.34739381],
       [ 54.81967824],
       [ 71.02422778],
       [ 62.14626814],
       [ 53.28005406],
       [ 49.88135643],
       [ 44.63510982],
       [ 61.79677392],
       [ 56.58994763],
       [ 28.41041805],
       [  8.07515358],
       [ 69.1724322 ],
       [ 65.92081244],
       [ 47.99755157],
       [ 41.63166837],
       [ 88.54151359],
       [ 62.48411292],
       [ 47.4998131 ],
       [109.0021822 ],
       [ 28.24207523],
       [ 46.05850625],
       [ 53.71001987],
       [ 60.93316339],
       [ 49.20380447],
       [ 20.94794145],
       [ 39.4613905 ],
       [ 79.207179  ],
       [ 73.15228551],
       [ 37.88125914],
       [ 31.92608629],
       [ 59.39882511],
       [ 38.8887956 ],
       [ 92.27139754],
       [ 30.11280243],
       [ 32.81334067],
       [ 41.12381317],
       [ 34.34685629],
       [ 44.37161984],
       [ 36.41565038],
       [ 44.71552634],
       [ 93.28941107],
       [ 55.16775053],
       [ 17.531676  ],
       [ 51.24222144],
       [ -1.55578407],
       [ 78.863067  ],
       [ 27.63473744],
       [ 60.41608394],
       [ 43.09521146],
       [ 35.65719139],
       [ 66.24607134],
       [ 44.33267861],
       [ 35.56765449],
       [ 74.73098021],
       [ 64.85788981],
       [ 25.53750048],
       [105.10625553],
       [ 62.31448096],
       [ 35.21445243],
       [ 48.1805925 ],
       [ 88.3179068 ],
       [ 37.16855708],
       [ 83.60874768],
       [ 34.11149479],
       [ 51.09497423],
       [ 47.69058363],
       [ 50.6400034 ],
       [ 54.48480161],
       [ 60.06329607],
       [ 54.85699063],
       [ 30.16094648],
       [ 21.93125953],
       [ 81.59814887],
       [ 65.64946356],
       [ 29.73337851],
       [ 74.32994776],
       [ 44.87739185],
       [ 71.84728997],
       [ 46.95936398],
       [ 14.65314456],
       [ 69.61270922],
       [ 64.54158166],
       [ 11.21982781],
       [ 46.2859713 ],
       [ 47.00678239],
       [  1.70775319],
       [ 16.52761283],
       [ 42.92655831],
       [ 33.4919753 ],
       [ 63.76739569],
       [ 26.43093185],
       [ 51.63732217],
       [ 42.2232212 ],
       [ 62.67056136],
       [ 45.55440184],
       [ 53.3874901 ],
       [ 24.78776743],
       [ 95.36119445],
       [ 73.81410367],
       [ 33.1384009 ]])

In [12]:
from sklearn.metrics import root_mean_squared_error
print(root_mean_squared_error(y_test,pred1))

18.735232365128752

In [13]:
print(root_mean_squared_error(y_test,pred2))

18.735232365128756

In [14]:
pred1-pred2

array([[ 5.68434189e-14, -1.72665302e+01, -5.05247726e+01, ...,
         2.38758564e-01, -2.13083322e+01, -6.19840350e+01],
       [ 1.72665302e+01,  4.26325641e-14, -3.32582424e+01, ...,
         1.75052888e+01, -4.04180201e+00, -4.47175048e+01],
       [ 5.05247726e+01,  3.32582424e+01,  0.00000000e+00, ...,
         5.07635312e+01,  2.92164404e+01, -1.14592623e+01],
       ...,
       [-2.38758564e-01, -1.75052888e+01, -5.07635312e+01, ...,
         2.84217094e-14, -2.15470908e+01, -6.22227935e+01],
       [ 2.13083322e+01,  4.04180201e+00, -2.92164404e+01, ...,
         2.15470908e+01, -1.42108547e-14, -4.06757028e+01],
       [ 6.19840350e+01,  4.47175048e+01,  1.14592623e+01, ...,
         6.22227935e+01,  4.06757028e+01, -7.10542736e-14]],
      shape=(160, 160))