In [2]:
import pandas as pd
import numpy as np
from mysql import connector as cnn
import os
from dotenv import load_dotenv
load_dotenv()
df=pd.read_csv(os.getenv("filepath"))
df

,Unnamed: 0,Student_ID,previous_gpa,attendance_percent,internal_assessment_marks,failed_subjects,study_hours_per_week,current_course_load,academic_risk_percentage
0,0,1,7.77,75.8,76.6,0,11.1,6,13.9
1,1,2,7.04,94.5,69.2,0,11.5,5,21.1
2,2,3,7.94,70.2,75.6,0,10.9,6,18.2
3,3,4,8.95,68.4,85.0,0,16.9,7,21.1
4,4,5,6.93,72.2,80.5,0,14.1,8,71.1
...,...,...,...,...,...,...,...,...,...
795,795,796,8.41,60.6,64.0,0,16.0,4,20.2
796,796,797,7.15,66.9,80.3,1,12.6,5,84.5
797,797,798,7.98,66.0,75.1,0,5.6,7,34.5
798,798,799,7.23,80.5,69.5,0,16.4,8,26.0
799,799,800,7.23,78.8,72.2,1,4.8,7,18.0

In [3]:
df['Student_ID']=pd.Series(np.arange(1,801,dtype=int))
df

,Unnamed: 0,Student_ID,previous_gpa,attendance_percent,internal_assessment_marks,failed_subjects,study_hours_per_week,current_course_load,academic_risk_percentage
0,0,1,7.77,75.8,76.6,0,11.1,6,13.9
1,1,2,7.04,94.5,69.2,0,11.5,5,21.1
2,2,3,7.94,70.2,75.6,0,10.9,6,18.2
3,3,4,8.95,68.4,85.0,0,16.9,7,21.1
4,4,5,6.93,72.2,80.5,0,14.1,8,71.1
...,...,...,...,...,...,...,...,...,...
795,795,796,8.41,60.6,64.0,0,16.0,4,20.2
796,796,797,7.15,66.9,80.3,1,12.6,5,84.5
797,797,798,7.98,66.0,75.1,0,5.6,7,34.5
798,798,799,7.23,80.5,69.5,0,16.4,8,26.0
799,799,800,7.23,78.8,72.2,1,4.8,7,18.0

In [4]:
df=df.drop(columns=['Unnamed: 0'])
df

,Student_ID,previous_gpa,attendance_percent,internal_assessment_marks,failed_subjects,study_hours_per_week,current_course_load,academic_risk_percentage
0,1,7.77,75.8,76.6,0,11.1,6,13.9
1,2,7.04,94.5,69.2,0,11.5,5,21.1
2,3,7.94,70.2,75.6,0,10.9,6,18.2
3,4,8.95,68.4,85.0,0,16.9,7,21.1
4,5,6.93,72.2,80.5,0,14.1,8,71.1
...,...,...,...,...,...,...,...,...
795,796,8.41,60.6,64.0,0,16.0,4,20.2
796,797,7.15,66.9,80.3,1,12.6,5,84.5
797,798,7.98,66.0,75.1,0,5.6,7,34.5
798,799,7.23,80.5,69.5,0,16.4,8,26.0
799,800,7.23,78.8,72.2,1,4.8,7,18.0

In [5]:
col=['Student_ID']+[i for i in df.columns if i!='Student_ID']
col

['Student_ID',
 'previous_gpa',
 'attendance_percent',
 'internal_assessment_marks',
 'failed_subjects',
 'study_hours_per_week',
 'current_course_load',
 'academic_risk_percentage']

In [6]:
df1=df[col]
df1

,Student_ID,previous_gpa,attendance_percent,internal_assessment_marks,failed_subjects,study_hours_per_week,current_course_load,academic_risk_percentage
0,1,7.77,75.8,76.6,0,11.1,6,13.9
1,2,7.04,94.5,69.2,0,11.5,5,21.1
2,3,7.94,70.2,75.6,0,10.9,6,18.2
3,4,8.95,68.4,85.0,0,16.9,7,21.1
4,5,6.93,72.2,80.5,0,14.1,8,71.1
...,...,...,...,...,...,...,...,...
795,796,8.41,60.6,64.0,0,16.0,4,20.2
796,797,7.15,66.9,80.3,1,12.6,5,84.5
797,798,7.98,66.0,75.1,0,5.6,7,34.5
798,799,7.23,80.5,69.5,0,16.4,8,26.0
799,800,7.23,78.8,72.2,1,4.8,7,18.0

In [7]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Student_ID                 800 non-null    int64
 1   previous_gpa               800 non-null    float64
 2   attendance_percent         800 non-null    float64
 3   internal_assessment_marks  800 non-null    float64
 4   failed_subjects            800 non-null    int64
 5   study_hours_per_week       800 non-null    float64
 6   current_course_load        800 non-null    int64
 7   academic_risk_percentage   800 non-null    float64
dtypes: float64(5), int64(3)
memory usage: 50.1 KB

In [8]:
df1.to_csv(r"C:\Users\chait\Downloads\academic_risk_percentage.csv")

In [9]:
conn=cnn.connect(
    host='localhost',
    user='root',
    password='Yashu@260707'
)
cur=conn.cursor()
cur.execute("CREATE DATABASE IF NOT EXISTS STUDENT")
cur.execute("USE STUDENT")
cur.execute(''' CREATE TABLE IF NOT EXISTS ACAD_PERF(
ST_ID INT PRIMARY KEY,
PREV_GPA DECIMAL,
ATTENDANCE DECIMAL,
INTERNALS DECIMAL,
BACKLOGS INT,
STUDY_HRS_PER_WEEK DECIMAL,
CURRENT_COURSE_LOAD INT,
ACADEMIC_RISK DECIMAL
);
''')

In [10]:
records=[]
for i in range(800):
    records.append(tuple(df1.iloc[i]))
records

[(1.0, 7.77, 75.8, 76.6, 0.0, 11.1, 6.0, 13.9),
 (2.0, 7.04, 94.5, 69.2, 0.0, 11.5, 5.0, 21.1),
 (3.0, 7.94, 70.2, 75.6, 0.0, 10.9, 6.0, 18.2),
 (4.0, 8.95, 68.4, 85.0, 0.0, 16.9, 7.0, 21.1),
 (5.0, 6.93, 72.2, 80.5, 0.0, 14.1, 8.0, 71.1),
 (6.0, 6.93, 66.6, 78.5, 0.0, 13.1, 7.0, 43.9),
 (7.0, 9.02, 79.5, 80.9, 0.0, 5.6, 6.0, 23.0),
 (8.0, 8.08, 97.5, 85.1, 0.0, 10.1, 8.0, 25.3),
 (9.0, 6.66, 81.9, 79.4, 2.0, 16.5, 6.0, 81.3),
 (10.0, 7.82, 75.0, 64.6, 0.0, 12.2, 7.0, 21.6),
 (11.0, 6.67, 74.5, 72.3, 1.0, 15.3, 6.0, 27.8),
 (12.0, 6.66, 59.2, 76.7, 0.0, 20.8, 7.0, 68.9),
 (13.0, 7.48, 88.6, 73.0, 1.0, 17.2, 6.0, 33.5),
 (14.0, 5.0, 77.1, 43.6, 1.0, 12.5, 6.0, 78.7),
 (15.0, 5.22, 75.8, 65.5, 2.0, 9.4, 6.0, 93.4),
 (16.0, 6.55, 100.0, 60.3, 1.0, 2.0, 8.0, 83.2),
 (17.0, 6.04, 81.6, 66.1, 2.0, 11.2, 5.0, 85.3),
 (18.0, 7.56, 69.0, 82.8, 0.0, 10.4, 5.0, 34.4),
 (19.0, 6.16, 72.9, 65.1, 2.0, 14.0, 9.0, 85.7),
 (20.0, 5.58, 91.8, 50.5, 1.0, 11.2, 7.0, 76.7),
 (21.0, 8.89, 79.4, 94.6, 0.0, 10.4, 3.0, 27.3),
 (22.0, 6.94, 60.7, 85.8, 0.0, 3.1, 5.0, 80.5),
 (23.0, 7.28, 89.0, 82.4, 0.0, 7.3, 4.0, 24.9),
 (24.0, 5.56, 70.0, 53.5, 2.0, 14.4, 5.0, 83.8),
 (25.0, 6.57, 100.0, 51.3, 1.0, 20.6, 3.0, 61.6),
 (26.0, 7.33, 91.0, 84.7, 0.0, 11.5, 6.0, 17.5),
 (27.0, 5.88, 72.6, 71.2, 1.0, 13.6, 5.0, 86.1),
 (28.0, 7.63, 93.4, 73.2, 1.0, 16.8, 6.0, 36.4),
 (29.0, 6.51, 78.8, 72.0, 2.0, 7.9, 4.0, 86.5),
 (30.0, 6.86, 88.2, 64.6, 0.0, 13.8, 6.0, 26.7),
 (31.0, 6.51, 83.8, 62.9, 1.0, 8.3, 6.0, 88.4),
 (32.0, 9.33, 67.8, 80.6, 0.0, 16.3, 8.0, 36.2),
 (33.0, 7.18, 70.3, 66.6, 1.0, 12.8, 8.0, 68.5),
 (34.0, 5.98, 90.4, 54.6, 2.0, 13.5, 7.0, 76.1),
 (35.0, 8.15, 74.0, 83.1, 0.0, 8.1, 6.0, 24.0),
 (36.0, 5.8, 73.2, 56.2, 1.0, 15.5, 8.0, 68.3),
 (37.0, 7.44, 66.5, 81.1, 0.0, 22.4, 4.0, 27.1),
 (38.0, 4.95, 83.1, 51.1, 1.0, 7.0, 4.0, 90.6),
 (39.0, 5.67, 100.0, 58.2, 3.0, 10.3, 6.0, 72.3),
 (40.0, 7.43, 65.2, 60.3, 0.0, 13.2, 9.0, 77.5),
 (41.0, 8.05, 78.3, 94.2, 0.0, 15.9, 6.0, 22.0),
 (42.0, 7.4, 94.9, 88.4, 0.0, 9.2, 6.0, 27.7),
 (43.0, 7.07, 77.0, 54.7, 1.0, 2.0, 4.0, 84.4),
 (44.0, 6.85, 83.4, 76.0, 0.0, 18.8, 7.0, 13.0),
 (45.0, 5.5, 65.3, 51.8, 3.0, 15.8, 7.0, 88.8),
 (46.0, 6.37, 83.1, 68.3, 1.0, 3.3, 7.0, 69.4),
 (47.0, 6.67, 75.8, 70.5, 0.0, 9.0, 5.0, 76.4),
 (48.0, 8.42, 89.8, 94.6, 0.0, 19.8, 5.0, 27.8),
 (49.0, 7.6, 92.2, 66.5, 0.0, 19.2, 4.0, 26.4),
 (50.0, 5.17, 100.0, 43.5, 2.0, 16.7, 6.0, 82.2),
 (51.0, 7.57, 85.0, 65.3, 0.0, 11.1, 5.0, 69.6),
 (52.0, 6.76, 81.9, 58.1, 3.0, 12.4, 5.0, 79.1),
 (53.0, 6.42, 80.3, 60.5, 1.0, 11.3, 5.0, 22.5),
 (54.0, 7.9, 73.8, 79.3, 0.0, 17.6, 5.0, 24.6),
 (55.0, 8.39, 82.1, 96.4, 0.0, 7.6, 5.0, 28.0),
 (56.0, 8.27, 74.5, 91.8, 1.0, 8.0, 7.0, 28.2),
 (57.0, 6.23, 80.0, 53.5, 2.0, 17.1, 6.0, 96.5),
 (58.0, 6.84, 93.8, 72.7, 1.0, 11.8, 6.0, 87.1),
 (59.0, 7.58, 65.9, 77.0, 0.0, 18.9, 6.0, 33.2),
 (60.0, 8.32, 91.7, 90.2, 0.0, 8.6, 5.0, 14.2),
 (61.0, 6.65, 93.8, 68.1, 0.0, 11.7, 6.0, 77.7),
 (62.0, 6.99, 76.6, 68.2, 0.0, 7.4, 6.0, 84.8),
 (63.0, 5.93, 52.5, 70.9, 1.0, 12.0, 4.0, 74.7),
 (64.0, 5.82, 70.7, 57.3, 0.0, 4.6, 7.0, 67.5),
 (65.0, 8.13, 93.6, 85.2, 0.0, 9.6, 5.0, 27.5),
 (66.0, 8.76, 77.7, 92.8, 0.0, 4.8, 6.0, 20.2),
 (67.0, 7.12, 66.0, 66.5, 0.0, 15.5, 7.0, 83.5),
 (68.0, 8.35, 71.9, 85.5, 0.0, 15.6, 7.0, 22.9),
 (69.0, 7.62, 88.1, 84.9, 0.0, 3.3, 6.0, 26.7),
 (70.0, 6.46, 84.6, 73.0, 0.0, 18.7, 6.0, 22.2),
 (71.0, 7.62, 75.1, 83.9, 2.0, 24.5, 7.0, 80.7),
 (72.0, 8.97, 73.6, 98.0, 0.0, 12.2, 7.0, 8.3),
 (73.0, 7.16, 73.3, 58.4, 0.0, 8.8, 5.0, 20.2),
 (74.0, 9.0, 66.9, 75.3, 0.0, 26.1, 5.0, 14.9),
 (75.0, 4.19, 97.4, 44.1, 2.0, 5.4, 4.0, 93.4),
 (76.0, 8.15, 74.1, 96.2, 0.0, 12.1, 6.0, 16.5),
 (77.0, 7.3, 92.6, 68.6, 0.0, 12.9, 6.0, 22.4),
 (78.0, 6.86, 96.3, 81.3, 1.0, 18.7, 7.0, 31.1),
 (79.0, 7.31, 90.0, 62.3, 0.0, 13.8, 6.0, 20.3),
 (80.0, 4.91, 72.8, 60.6, 3.0, 9.5, 8.0, 79.2),
 (81.0, 6.95, 82.8, 77.3, 1.0, 7.2, 5.0, 25.7),
 (82.0, 7.61, 77.7, 87.2, 1.0, 10.3, 7.0, 30.9),
 (83.0, 8.9, 67.2, 98.0, 0.0, 7.0, 5.0, 24.8),
 (84.0, 6.6, 81.9, 65.1, 1.0, 12.2, 7.0, 75.1),
 (85.0, 6.27, 63.9, 61.7, 1.0, 9.2, 4.0, 91.7),
 (86.0, 6.62, 92.3, 82.3, 0.0, 4.5, 6.0, 22.8),
 (87.0, 8.25, 72.4, 82.3, 0.0, 18.3, 4.0, 30.2),
 (88.0, 7.58, 80.4, 73.6, 1.0, 9.5, 6.0, 24.1),
 (89.0, 6.59, 81.4, 69.1, 1.0, 5.7, 7.0, 88.2),
 (90.0, 7.79, 74.9, 68.1, 0.0, 11.2, 5.0, 22.1),
 (91.0, 7.31, 85.0, 77.1, 0.0, 12.3, 5.0, 19.4),
 (92.0, 8.31, 72.3, 80.2, 0.0, 3.3, 7.0, 66.8),
 (93.0, 6.39, 88.5, 65.3, 0.0, 13.7, 6.0, 22.9),
 (94.0, 6.82, 61.8, 85.6, 0.0, 6.8, 5.0, 19.6),
 (95.0, 6.75, 79.5, 64.3, 0.0, 20.6, 6.0, 23.7),
 (96.0, 5.52, 100.0, 64.9, 2.0, 14.6, 9.0, 78.2),
 (97.0, 7.54, 66.0, 72.3, 0.0, 10.0, 7.0, 37.7),
 (98.0, 7.5, 69.9, 73.5, 0.0, 8.3, 7.0, 86.3),
 (99.0, 7.21, 84.2, 84.4, 1.0, 11.5, 7.0, 41.3),
 (100.0, 6.93, 80.2, 67.9, 1.0, 15.1, 6.0, 75.4),
 (101.0, 5.57, 82.2, 62.1, 1.0, 11.9, 3.0, 73.9),
 (102.0, 6.72, 83.9, 72.9, 0.0, 10.9, 5.0, 78.8),
 (103.0, 6.81, 85.6, 65.6, 0.0, 12.3, 5.0, 24.9),
 (104.0, 6.28, 91.3, 64.3, 1.0, 9.0, 4.0, 85.4),
 (105.0, 7.01, 82.9, 62.4, 1.0, 10.3, 5.0, 18.2),
 (106.0, 7.66, 75.1, 70.3, 1.0, 2.0, 4.0, 28.7),
 (107.0, 9.37, 86.1, 98.0, 0.0, 16.9, 6.0, 10.2),
 (108.0, 7.4, 100.0, 87.7, 0.0, 13.5, 7.0, 11.3),
 (109.0, 7.5, 76.4, 67.4, 0.0, 8.1, 7.0, 30.2),
 (110.0, 7.11, 66.3, 71.4, 0.0, 21.5, 6.0, 75.3),
 (111.0, 4.99, 91.3, 52.3, 2.0, 12.4, 5.0, 97.0),
 (112.0, 7.17, 76.6, 77.2, 1.0, 6.8, 4.0, 28.6),
 (113.0, 7.27, 51.9, 78.3, 1.0, 16.3, 4.0, 36.6),
 (114.0, 10.0, 88.2, 96.0, 0.0, 14.0, 4.0, 9.9),
 (115.0, 6.98, 71.6, 68.3, 0.0, 14.0, 5.0, 70.0),
 (116.0, 7.55, 76.9, 79.5, 0.0, 9.9, 6.0, 26.2),
 (117.0, 7.16, 82.0, 75.3, 1.0, 14.3, 5.0, 76.6),
 (118.0, 5.86, 80.3, 41.7, 1.0, 10.7, 6.0, 79.8),
 (119.0, 8.51, 86.5, 81.1, 0.0, 14.8, 6.0, 7.9),
 (120.0, 8.06, 72.8, 74.8, 1.0, 2.5, 6.0, 74.7),
 (121.0, 8.11, 84.2, 87.9, 1.0, 9.8, 7.0, 19.3),
 (122.0, 6.15, 74.9, 80.3, 1.0, 20.6, 5.0, 83.9),
 (123.0, 8.81, 86.9, 91.7, 0.0, 8.2, 7.0, 25.9),
 (124.0, 5.59, 85.4, 49.9, 3.0, 9.0, 6.0, 84.3),
 (125.0, 7.87, 66.8, 92.1, 0.0, 9.8, 6.0, 35.8),
 (126.0, 9.72, 91.0, 93.4, 0.0, 5.9, 7.0, 20.7),
 (127.0, 6.06, 71.6, 61.2, 1.0, 2.0, 7.0, 70.5),
 (128.0, 6.55, 87.7, 72.2, 1.0, 10.8, 5.0, 78.3),
 (129.0, 7.31, 82.4, 97.4, 0.0, 12.7, 6.0, 24.5),
 (130.0, 6.62, 100.0, 56.8, 1.0, 11.7, 6.0, 68.8),
 (131.0, 5.42, 75.3, 55.2, 3.0, 11.3, 6.0, 88.3),
 (132.0, 7.28, 73.8, 74.8, 0.0, 12.2, 7.0, 71.2),
 (133.0, 5.98, 77.8, 57.0, 2.0, 17.1, 6.0, 83.9),
 (134.0, 7.74, 74.4, 59.1, 1.0, 11.0, 8.0, 34.8),
 (135.0, 6.14, 87.6, 60.3, 1.0, 9.1, 4.0, 72.4),
 (136.0, 8.98, 58.6, 85.0, 0.0, 10.6, 6.0, 22.7),
 (137.0, 6.3, 65.4, 65.7, 1.0, 14.9, 5.0, 79.8),
 (138.0, 6.83, 65.2, 79.2, 2.0, 19.1, 7.0, 86.5),
 (139.0, 8.14, 89.4, 72.6, 0.0, 8.9, 4.0, 20.4),
 (140.0, 5.78, 98.5, 55.5, 0.0, 12.5, 6.0, 78.8),
 (141.0, 7.46, 76.7, 62.5, 1.0, 13.7, 5.0, 85.6),
 (142.0, 8.7, 76.0, 81.3, 0.0, 7.0, 5.0, 19.9),
 (143.0, 5.35, 78.8, 55.0, 2.0, 12.1, 4.0, 91.6),
 (144.0, 7.41, 91.9, 71.2, 0.0, 4.7, 5.0, 26.8),
 (145.0, 7.5, 66.9, 98.0, 1.0, 3.2, 7.0, 42.8),
 (146.0, 8.1, 80.9, 79.1, 0.0, 13.8, 6.0, 26.3),
 (147.0, 5.78, 89.7, 39.1, 1.0, 10.1, 7.0, 77.6),
 (148.0, 5.68, 84.0, 48.8, 0.0, 13.0, 8.0, 70.1),
 (149.0, 7.8, 80.3, 85.9, 0.0, 11.9, 6.0, 26.0),
 (150.0, 7.54, 90.0, 93.3, 0.0, 7.1, 5.0, 8.9),
 (151.0, 7.49, 45.6, 61.0, 0.0, 11.8, 7.0, 71.5),
 (152.0, 7.6, 86.1, 62.7, 1.0, 5.8, 5.0, 31.3),
 (153.0, 6.42, 70.2, 72.9, 1.0, 19.0, 5.0, 81.2),
 (154.0, 7.47, 56.0, 85.0, 1.0, 5.2, 4.0, 29.7),
 (155.0, 7.54, 84.1, 68.0, 0.0, 11.0, 7.0, 34.9),
 (156.0, 6.38, 94.5, 73.6, 0.0, 6.8, 6.0, 79.2),
 (157.0, 9.35, 76.4, 74.1, 0.0, 14.9, 6.0, 11.5),
 (158.0, 7.74, 89.4, 79.8, 1.0, 10.3, 5.0, 25.7),
 (159.0, 5.83, 97.3, 63.8, 1.0, 9.4, 7.0, 84.8),
 (160.0, 7.96, 93.8, 89.2, 0.0, 16.3, 5.0, 30.6),
 (161.0, 6.08, 97.7, 55.9, 1.0, 12.1, 6.0, 82.6),
 (162.0, 8.11, 86.9, 88.4, 0.0, 14.6, 7.0, 23.6),
 (163.0, 8.53, 78.9, 78.9, 0.0, 7.1, 7.0, 20.4),
 (164.0, 6.26, 58.8, 68.2, 1.0, 5.0, 6.0, 92.0),
 (165.0, 8.31, 75.0, 75.5, 0.0, 12.5, 4.0, 13.4),
 (166.0, 7.67, 67.9, 80.7, 0.0, 10.4, 9.0, 32.1),
 (167.0, 8.15, 100.0, 70.1, 0.0, 15.1, 8.0, 20.4),
 (168.0, 9.38, 75.9, 98.0, 0.0, 11.6, 7.0, 20.0),
 (169.0, 6.92, 79.5, 75.8, 0.0, 13.0, 5.0, 73.9),
 (170.0, 6.33, 84.6, 54.3, 2.0, 3.9, 6.0, 83.8),
 (171.0, 6.18, 78.5, 62.7, 2.0, 21.4, 5.0, 76.2),
 (172.0, 6.26, 98.3, 47.6, 1.0, 11.2, 8.0, 68.1),
 (173.0, 7.11, 70.5, 72.9, 0.0, 15.5, 6.0, 25.8),
 (174.0, 7.59, 80.3, 72.3, 0.0, 7.8, 5.0, 66.5),
 (175.0, 7.52, 69.1, 93.9, 0.0, 13.5, 5.0, 40.9),
 (176.0, 8.15, 62.2, 63.2, 0.0, 5.5, 7.0, 22.3),
 (177.0, 7.21, 70.7, 81.6, 1.0, 14.3, 8.0, 69.6),
 (178.0, 8.87, 77.6, 84.6, 0.0, 10.2, 8.0, 24.9),
 (179.0, 6.9, 72.8, 63.3, 1.0, 12.1, 7.0, 84.7),
 (180.0, 10.0, 69.7, 98.0, 0.0, 15.5, 6.0, 22.2),
 (181.0, 7.92, 61.1, 86.1, 0.0, 5.8, 3.0, 38.0),
 (182.0, 6.21, 77.0, 67.4, 2.0, 8.6, 6.0, 83.3),
 (183.0, 5.97, 59.9, 54.4, 1.0, 14.3, 6.0, 76.4),
 (184.0, 7.75, 87.1, 87.1, 0.0, 22.5, 6.0, 11.5),
 (185.0, 6.94, 79.0, 78.2, 1.0, 11.3, 6.0, 33.8),
 (186.0, 8.02, 60.5, 69.4, 1.0, 15.0, 4.0, 81.2),
 (187.0, 7.74, 74.3, 74.4, 0.0, 11.5, 7.0, 32.4),
 (188.0, 7.12, 69.0, 73.9, 0.0, 21.7, 7.0, 18.7),
 (189.0, 6.23, 81.8, 54.8, 1.0, 3.3, 7.0, 72.4),
 (190.0, 5.46, 94.1, 54.2, 4.0, 12.5, 7.0, 84.0),
 (191.0, 6.69, 55.5, 77.8, 0.0, 3.9, 7.0, 77.5),
 (192.0, 8.18, 79.4, 68.0, 0.0, 2.0, 6.0, 80.6),
 (193.0, 7.45, 76.1, 72.9, 0.0, 13.5, 6.0, 39.0),
 (194.0, 5.77, 86.1, 54.7, 2.0, 12.7, 6.0, 79.1),
 (195.0, 7.4, 80.6, 75.8, 0.0, 10.6, 6.0, 19.2),
 (196.0, 7.64, 69.0, 57.1, 0.0, 11.5, 7.0, 83.1),
 (197.0, 6.18, 74.2, 66.0, 2.0, 27.5, 7.0, 75.9),
 (198.0, 7.38, 68.4, 78.7, 3.0, 10.7, 8.0, 90.0),
 (199.0, 7.27, 90.9, 79.4, 1.0, 14.6, 9.0, 36.1),
 (200.0, 5.89, 78.3, 57.8, 1.0, 8.8, 6.0, 75.8),
 (201.0, 7.61, 100.0, 68.1, 0.0, 13.5, 3.0, 10.9),
 (202.0, 7.84, 77.3, 88.0, 0.0, 10.8, 7.0, 11.7),
 (203.0, 8.45, 69.5, 79.7, 0.0, 9.9, 5.0, 35.1),
 (204.0, 8.41, 59.8, 71.4, 0.0, 21.1, 5.0, 27.0),
 (205.0, 5.62, 56.4, 54.7, 2.0, 17.9, 6.0, 90.3),
 (206.0, 6.12, 59.0, 61.7, 0.0, 12.7, 5.0, 88.4),
 (207.0, 7.79, 81.2, 77.6, 1.0, 2.0, 7.0, 23.2),
 (208.0, 7.79, 84.1, 63.4, 0.0, 10.2, 4.0, 13.6),
 (209.0, 7.79, 59.0, 90.3, 0.0, 25.5, 5.0, 38.2),
 (210.0, 10.0, 88.7, 98.0, 0.0, 10.8, 6.0, 8.4),
 (211.0, 7.86, 72.2, 90.4, 1.0, 17.5, 7.0, 28.3),
 (212.0, 8.51, 79.8, 76.9, 0.0, 19.2, 7.0, 24.3),
 (213.0, 8.3, 97.3, 91.7, 0.0, 13.1, 5.0, 16.9),
 (214.0, 7.95, 88.8, 76.0, 0.0, 7.8, 5.0, 14.7),
 (215.0, 6.84, 74.8, 81.8, 1.0, 2.0, 5.0, 83.8),
 (216.0, 8.07, 67.3, 87.1, 0.0, 15.4, 6.0, 31.5),
 (217.0, 6.31, 52.2, 54.0, 0.0, 7.9, 8.0, 72.3),
 (218.0, 6.93, 69.4, 67.5, 2.0, 12.9, 4.0, 91.3),
 (219.0, 6.64, 75.5, 68.5, 1.0, 5.8, 6.0, 79.1),
 (220.0, 7.29, 66.2, 86.7, 0.0, 10.7, 4.0, 38.7),
 (221.0, 9.86, 76.4, 98.0, 0.0, 12.2, 4.0, 11.4),
 (222.0, 5.05, 78.9, 54.0, 1.0, 13.3, 7.0, 91.6),
 (223.0, 7.99, 75.3, 80.4, 0.0, 6.4, 7.0, 31.5),
 (224.0, 5.35, 70.2, 75.4, 0.0, 18.0, 7.0, 83.7),
 (225.0, 6.66, 80.0, 78.5, 2.0, 9.0, 7.0, 82.9),
 (226.0, 8.45, 83.3, 79.8, 0.0, 3.6, 5.0, 28.6),
 (227.0, 7.27, 64.9, 84.2, 0.0, 11.5, 5.0, 36.6),
 (228.0, 5.96, 94.9, 65.8, 1.0, 12.2, 9.0, 76.3),
 (229.0, 6.38, 76.8, 63.3, 2.0, 12.8, 6.0, 79.5),
 (230.0, 7.98, 78.2, 70.9, 0.0, 18.8, 7.0, 34.4),
 (231.0, 6.36, 86.5, 64.7, 0.0, 10.8, 6.0, 63.0),
 (232.0, 7.45, 80.8, 69.9, 1.0, 11.4, 4.0, 36.9),
 (233.0, 7.25, 89.4, 76.1, 1.0, 6.5, 4.0, 22.4),
 (234.0, 6.45, 81.4, 70.2, 1.0, 16.1, 5.0, 78.3),
 (235.0, 9.67, 70.7, 98.0, 0.0, 12.9, 7.0, 26.6),
 (236.0, 7.93, 82.3, 95.7, 2.0, 9.9, 7.0, 23.9),
 (237.0, 4.87, 64.3, 44.1, 4.0, 2.5, 7.0, 93.3),
 (238.0, 7.41, 79.3, 74.4, 0.0, 19.2, 5.0, 81.7),
 (239.0, 6.44, 77.6, 57.3, 2.0, 5.9, 8.0, 97.0),
 (240.0, 8.18, 75.5, 90.2, 0.0, 9.0, 5.0, 15.1),
 (241.0, 6.29, 76.5, 85.8, 1.0, 13.8, 6.0, 78.6),
 (242.0, 7.07, 55.4, 66.6, 0.0, 6.0, 6.0, 73.5),
 (243.0, 7.78, 71.4, 76.4, 0.0, 4.5, 6.0, 10.6),
 (244.0, 8.2, 79.1, 76.5, 0.0, 2.0, 8.0, 13.6),
 (245.0, 5.82, 79.9, 48.6, 2.0, 15.6, 5.0, 88.3),
 (246.0, 6.82, 65.7, 66.3, 1.0, 9.3, 4.0, 70.6),
 (247.0, 6.65, 93.2, 66.8, 0.0, 26.6, 6.0, 77.8),
 (248.0, 6.45, 67.6, 45.4, 1.0, 7.0, 6.0, 84.8),
 (249.0, 9.23, 89.6, 98.0, 0.0, 7.4, 9.0, 15.6),
 (250.0, 7.67, 83.1, 90.8, 0.0, 9.2, 7.0, 27.0),
 (251.0, 5.75, 70.2, 47.1, 2.0, 13.2, 6.0, 83.6),
 (252.0, 8.26, 99.3, 96.7, 0.0, 9.6, 5.0, 22.7),
 (253.0, 9.64, 63.7, 98.0, 0.0, 15.1, 4.0, 20.5),
 (254.0, 8.39, 89.0, 93.4, 0.0, 7.1, 5.0, 29.9),
 (255.0, 5.45, 90.0, 46.5, 1.0, 5.1, 6.0, 79.0),
 (256.0, 6.64, 70.0, 69.9, 0.0, 3.0, 8.0, 66.3),
 (257.0, 8.66, 94.7, 77.7, 0.0, 2.0, 7.0, 17.2),
 (258.0, 6.39, 75.0, 76.8, 1.0, 9.4, 6.0, 81.5),
 (259.0, 7.71, 81.5, 81.2, 0.0, 10.5, 6.0, 16.3),
 (260.0, 8.09, 81.1, 83.5, 0.0, 8.8, 6.0, 68.1),
 (261.0, 6.13, 76.4, 55.8, 1.0, 18.2, 5.0, 82.7),
 (262.0, 7.13, 87.7, 49.9, 1.0, 18.1, 8.0, 79.4),
 (263.0, 4.0, 87.5, 50.5, 3.0, 10.3, 6.0, 90.9),
 (264.0, 6.02, 57.0, 43.9, 0.0, 3.0, 6.0, 83.0),
 (265.0, 6.91, 93.7, 71.0, 1.0, 9.2, 3.0, 36.0),
 (266.0, 5.77, 58.1, 41.1, 1.0, 9.0, 6.0, 88.9),
 (267.0, 9.08, 90.4, 91.1, 0.0, 8.7, 7.0, 25.4),
 (268.0, 5.56, 91.5, 51.5, 3.0, 8.5, 5.0, 74.5),
 (269.0, 6.69, 64.9, 69.0, 1.0, 8.7, 5.0, 82.0),
 (270.0, 7.35, 73.1, 80.2, 0.0, 10.1, 7.0, 71.7),
 (271.0, 8.86, 64.7, 82.8, 0.0, 8.8, 4.0, 25.3),
 (272.0, 5.55, 75.4, 62.5, 1.0, 13.0, 7.0, 72.6),
 (273.0, 8.54, 74.3, 87.8, 0.0, 13.8, 5.0, 25.5),
 (274.0, 7.21, 87.4, 61.4, 0.0, 7.4, 6.0, 79.4),
 (275.0, 6.07, 93.7, 57.6, 1.0, 18.4, 5.0, 78.0),
 (276.0, 7.73, 94.7, 59.1, 0.0, 7.1, 6.0, 68.3),
 (277.0, 7.43, 71.3, 69.3, 0.0, 3.9, 9.0, 89.5),
 (278.0, 6.51, 75.5, 50.4, 2.0, 13.9, 7.0, 93.3),
 (279.0, 7.28, 57.8, 81.1, 0.0, 7.9, 5.0, 22.7),
 (280.0, 6.76, 68.3, 69.7, 2.0, 13.6, 7.0, 28.9),
 (281.0, 7.33, 89.6, 77.0, 0.0, 2.0, 6.0, 15.6),
 (282.0, 7.96, 97.4, 75.5, 0.0, 19.0, 8.0, 70.1),
 (283.0, 9.02, 63.2, 86.0, 0.0, 15.4, 7.0, 37.5),
 (284.0, 5.78, 70.9, 74.0, 1.0, 4.5, 3.0, 73.4),
 (285.0, 9.65, 77.7, 98.0, 0.0, 4.6, 5.0, 29.1),
 (286.0, 4.96, 81.4, 54.2, 4.0, 20.4, 7.0, 97.0),
 (287.0, 7.03, 68.3, 79.2, 0.0, 8.3, 6.0, 73.6),
 (288.0, 7.88, 83.1, 67.7, 0.0, 7.8, 5.0, 80.0),
 (289.0, 7.52, 72.3, 80.0, 0.0, 2.0, 5.0, 19.7),
 (290.0, 6.48, 77.8, 68.8, 0.0, 10.2, 4.0, 79.7),
 (291.0, 6.96, 84.6, 61.1, 0.0, 10.9, 6.0, 67.6),
 (292.0, 6.63, 78.1, 64.2, 0.0, 15.6, 9.0, 84.3),
 (293.0, 6.52, 72.8, 68.5, 0.0, 5.0, 7.0, 74.5),
 (294.0, 8.18, 76.7, 81.0, 1.0, 4.4, 9.0, 76.2),
 (295.0, 7.61, 76.9, 82.4, 0.0, 14.3, 7.0, 12.1),
 (296.0, 6.4, 73.6, 75.1, 1.0, 17.0, 7.0, 85.3),
 (297.0, 8.23, 74.9, 91.4, 0.0, 4.1, 8.0, 24.3),
 (298.0, 7.55, 97.2, 55.0, 0.0, 17.4, 6.0, 26.7),
 (299.0, 8.13, 84.7, 90.9, 0.0, 12.2, 6.0, 31.8),
 (300.0, 7.92, 74.5, 91.6, 0.0, 17.5, 7.0, 31.1),
 (301.0, 6.25, 86.4, 70.6, 2.0, 11.6, 8.0, 83.1),
 (302.0, 6.56, 74.0, 59.8, 1.0, 2.0, 5.0, 78.5),
 (303.0, 8.06, 92.1, 98.0, 0.0, 11.2, 5.0, 20.8),
 (304.0, 7.9, 82.4, 86.5, 0.0, 17.3, 6.0, 10.0),
 (305.0, 7.18, 76.7, 79.3, 1.0, 7.5, 7.0, 20.4),
 (306.0, 7.33, 83.4, 76.5, 0.0, 10.1, 7.0, 75.4),
 (307.0, 8.67, 59.1, 90.9, 0.0, 11.1, 4.0, 16.9),
 (308.0, 6.52, 64.5, 60.1, 1.0, 2.0, 8.0, 89.7),
 (309.0, 7.83, 63.7, 72.4, 0.0, 20.4, 5.0, 70.6),
 (310.0, 6.97, 79.7, 91.8, 0.0, 7.5, 6.0, 79.6),
 (311.0, 6.95, 98.8, 62.0, 0.0, 14.5, 5.0, 80.2),
 (312.0, 8.46, 100.0, 98.0, 1.0, 11.6, 9.0, 17.5),
 (313.0, 8.15, 85.7, 89.8, 0.0, 18.3, 6.0, 29.4),
 (314.0, 8.14, 84.0, 72.6, 0.0, 14.0, 5.0, 32.3),
 (315.0, 8.7, 56.4, 90.7, 0.0, 10.8, 7.0, 33.3),
 (316.0, 7.22, 71.5, 57.3, 1.0, 7.5, 7.0, 87.1),
 (317.0, 7.98, 68.5, 96.9, 1.0, 16.0, 6.0, 36.0),
 (318.0, 6.84, 70.5, 75.2, 0.0, 2.6, 7.0, 65.8),
 (319.0, 7.57, 76.0, 72.0, 0.0, 15.2, 5.0, 35.4),
 (320.0, 7.05, 72.3, 76.7, 1.0, 6.5, 5.0, 83.6),
 (321.0, 7.31, 54.2, 94.3, 0.0, 18.3, 4.0, 22.2),
 (322.0, 7.88, 87.0, 80.7, 0.0, 12.8, 4.0, 36.0),
 (323.0, 6.26, 65.1, 57.3, 1.0, 15.2, 8.0, 91.3),
 (324.0, 9.61, 80.9, 98.0, 0.0, 12.4, 8.0, 21.0),
 (325.0, 6.04, 100.0, 84.3, 2.0, 3.2, 6.0, 81.6),
 (326.0, 5.8, 67.0, 52.3, 1.0, 7.7, 8.0, 89.4),
 (327.0, 8.53, 47.6, 94.9, 0.0, 15.4, 6.0, 11.2),
 (328.0, 8.11, 74.6, 88.1, 0.0, 12.8, 6.0, 20.9),
 (329.0, 7.92, 91.2, 72.9, 0.0, 17.9, 6.0, 72.9),
 (330.0, 7.92, 100.0, 77.0, 0.0, 14.0, 6.0, 23.0),
 (331.0, 7.19, 63.2, 83.3, 1.0, 7.2, 6.0, 88.3),
 (332.0, 6.17, 84.0, 77.3, 2.0, 8.0, 7.0, 76.0),
 (333.0, 7.29, 72.4, 85.4, 0.0, 12.5, 6.0, 31.8),
 (334.0, 6.42, 76.7, 59.4, 1.0, 2.0, 7.0, 91.0),
 (335.0, 8.32, 100.0, 97.9, 0.0, 20.4, 7.0, 10.2),
 (336.0, 7.03, 60.0, 70.9, 0.0, 14.2, 6.0, 20.2),
 (337.0, 6.25, 81.0, 65.8, 1.0, 18.1, 5.0, 70.8),
 (338.0, 6.83, 83.6, 64.9, 1.0, 4.1, 4.0, 90.7),
 (339.0, 7.67, 91.0, 92.2, 0.0, 18.2, 6.0, 28.2),
 (340.0, 6.55, 79.2, 75.9, 0.0, 23.2, 6.0, 77.7),
 (341.0, 6.25, 81.7, 64.4, 1.0, 5.4, 6.0, 69.0),
 (342.0, 7.48, 73.3, 85.4, 0.0, 15.9, 6.0, 23.0),
 (343.0, 7.48, 81.2, 74.4, 1.0, 12.0, 9.0, 26.0),
 (344.0, 6.62, 73.9, 71.3, 0.0, 4.3, 4.0, 87.9),
 (345.0, 6.66, 85.5, 45.5, 1.0, 14.5, 4.0, 73.8),
 (346.0, 7.47, 73.6, 72.4, 0.0, 16.2, 6.0, 14.5),
 (347.0, 5.53, 82.5, 51.8, 1.0, 9.0, 6.0, 69.1),
 (348.0, 5.58, 77.6, 39.4, 1.0, 17.8, 6.0, 69.2),
 (349.0, 6.37, 91.5, 74.8, 1.0, 3.7, 7.0, 86.9),
 (350.0, 6.95, 77.4, 63.7, 1.0, 4.5, 8.0, 80.2),
 (351.0, 7.56, 56.7, 84.7, 2.0, 12.7, 4.0, 82.2),
 (352.0, 8.9, 93.1, 90.8, 0.0, 12.1, 5.0, 21.8),
 (353.0, 8.19, 67.1, 74.9, 0.0, 8.4, 7.0, 83.3),
 (354.0, 7.02, 70.2, 62.3, 0.0, 16.0, 7.0, 74.0),
 (355.0, 7.18, 70.9, 79.4, 0.0, 14.7, 9.0, 76.9),
 (356.0, 6.05, 94.5, 61.9, 1.0, 16.3, 7.0, 79.6),
 (357.0, 7.18, 52.4, 69.9, 0.0, 11.4, 6.0, 77.9),
 (358.0, 6.87, 100.0, 73.9, 3.0, 15.0, 5.0, 71.8),
 (359.0, 7.57, 90.7, 71.6, 0.0, 9.8, 5.0, 60.6),
 (360.0, 6.25, 80.7, 65.8, 0.0, 22.3, 5.0, 77.2),
 (361.0, 7.8, 77.3, 70.5, 0.0, 7.9, 7.0, 16.3),
 (362.0, 8.96, 81.4, 91.6, 0.0, 22.5, 6.0, 16.8),
 (363.0, 7.07, 84.3, 71.0, 0.0, 12.2, 4.0, 72.8),
 (364.0, 7.66, 85.7, 63.3, 0.0, 5.1, 5.0, 25.0),
 (365.0, 7.99, 84.7, 87.1, 0.0, 18.8, 7.0, 29.0),
 (366.0, 6.74, 79.1, 86.1, 1.0, 12.6, 6.0, 88.9),
 (367.0, 7.46, 75.6, 81.2, 0.0, 16.3, 7.0, 19.4),
 (368.0, 7.21, 76.2, 78.6, 0.0, 18.1, 6.0, 18.0),
 (369.0, 7.31, 75.7, 72.0, 0.0, 13.7, 8.0, 25.8),
 (370.0, 6.31, 91.6, 65.8, 0.0, 9.0, 6.0, 72.4),
 (371.0, 7.23, 85.1, 74.4, 0.0, 16.9, 6.0, 18.4),
 (372.0, 7.77, 42.7, 73.2, 0.0, 12.0, 5.0, 35.9),
 (373.0, 8.87, 85.9, 87.8, 0.0, 15.4, 6.0, 22.5),
 (374.0, 8.3, 80.3, 70.3, 0.0, 2.0, 3.0, 25.1),
 (375.0, 9.68, 77.8, 89.1, 0.0, 14.2, 6.0, 24.9),
 (376.0, 6.32, 73.3, 59.5, 2.0, 8.8, 6.0, 94.4),
 (377.0, 8.2, 91.5, 71.5, 0.0, 20.3, 4.0, 7.5),
 (378.0, 7.41, 89.4, 71.7, 0.0, 15.1, 5.0, 23.8),
 (379.0, 9.72, 68.7, 91.7, 0.0, 13.2, 7.0, 21.5),
 (380.0, 6.27, 82.9, 61.0, 1.0, 14.4, 6.0, 81.9),
 (381.0, 6.23, 66.3, 70.2, 1.0, 7.0, 6.0, 85.2),
 (382.0, 6.51, 61.4, 66.9, 0.0, 20.1, 6.0, 28.4),
 (383.0, 4.76, 70.5, 42.5, 2.0, 22.0, 6.0, 87.9),
 (384.0, 6.6, 88.3, 49.8, 1.0, 14.0, 7.0, 82.4),
 (385.0, 6.33, 89.4, 54.4, 2.0, 20.0, 6.0, 77.5),
 (386.0, 7.37, 84.2, 75.6, 0.0, 9.2, 4.0, 20.9),
 (387.0, 7.59, 86.7, 64.9, 0.0, 8.0, 8.0, 14.6),
 (388.0, 9.36, 84.2, 82.1, 0.0, 12.2, 6.0, 22.3),
 (389.0, 8.29, 70.3, 82.0, 0.0, 14.2, 5.0, 26.1),
 (390.0, 6.54, 83.2, 62.0, 2.0, 10.0, 4.0, 84.1),
 (391.0, 6.17, 87.6, 67.0, 1.0, 14.7, 6.0, 83.2),
 (392.0, 7.77, 87.1, 66.5, 0.0, 13.5, 6.0, 10.4),
 (393.0, 5.68, 92.3, 50.5, 2.0, 7.0, 8.0, 70.0),
 (394.0, 9.31, 86.5, 87.2, 0.0, 14.6, 6.0, 12.4),
 (395.0, 8.56, 82.2, 77.3, 0.0, 16.3, 5.0, 17.7),
 (396.0, 6.66, 90.8, 62.0, 0.0, 12.9, 7.0, 13.6),
 (397.0, 5.23, 77.7, 56.8, 3.0, 17.8, 7.0, 89.9),
 (398.0, 8.76, 67.4, 76.0, 0.0, 5.9, 6.0, 19.5),
 (399.0, 7.07, 76.0, 68.9, 0.0, 14.3, 7.0, 20.0),
 (400.0, 8.62, 69.1, 95.5, 0.0, 6.1, 6.0, 21.8),
 (401.0, 5.37, 69.9, 55.8, 1.0, 6.4, 6.0, 86.7),
 (402.0, 6.51, 76.3, 84.5, 0.0, 8.8, 7.0, 77.2),
 (403.0, 7.21, 68.5, 75.5, 0.0, 7.3, 7.0, 32.1),
 (404.0, 7.25, 74.3, 67.2, 1.0, 9.3, 6.0, 79.0),
 (405.0, 6.68, 55.3, 66.3, 3.0, 10.9, 8.0, 85.8),

In [11]:
query=f'''INSERT IGNORE INTO ACAD_PERF(ST_ID,
PREV_GPA,
ATTENDANCE,
INTERNALS,
BACKLOGS,
STUDY_HRS_PER_WEEK,
CURRENT_COURSE_LOAD,
ACADEMIC_RISK)
VALUES (%s,%s,%s,%s,%s,%s,%s,%s)
'''
cur.executemany(query,records)

In [12]:
conn.commit()
cur.close()
conn.close()